# Uncomment the next line to define a global platform for your project
#platform :ios, '9.0'

target 'iPad_TrueDepth_Issue_App' do
  platform :ios, '9.0'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iPad_TrueDepth_Issue_App
  pod "GCDWebServer", "~> 3.0"
  pod 'SKJavaScriptBridge', '~> 1.0.1'
  pod 'ZIPFoundation', '~> 0.9'
  pod 'OpenCV'

  post_install do |installer|
   installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
     config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
    end
   end
  end

end
